name: flutter_project
description: "A new Flutter project."
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=3.5.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  http: ^1.2.2
  web_socket_channel: ^3.0.1
  cupertino_icons: ^1.0.8
  flutter_map: ^7.0.2
  latlong2: ^0.9.1
  url_launcher: ^6.3.1
  fl_chart: ^0.69.2
  charts_flutter: ^0.12.0
  image_picker: ^1.1.2
  fluttertoast: ^8.2.8
  shared_preferences: ^2.1.2
  geocoding: ^2.0.2
  flutter_local_notifications: ^18.0.1
  permission_handler: ^11.3.1
  geolocator: ^13.0.2


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/images/

  fonts:
    - family: Metropolis
      fonts:
        - asset: assets/fonts/metropolis.medium.otf
          weight: 500
